export type OfficialName = {
  arabic: string;
  transliteration: string;
  meaning: string;
};

export const ASMA_UL_HUSNA: OfficialName[] = [
  { arabic: "ٱلرَّحْمَٰنُ", transliteration: "Ar-Rahmān", meaning: "The Most Merciful" },
  { arabic: "ٱلرَّحِيمُ", transliteration: "Ar-Raḥīm", meaning: "The Especially Merciful" },
  { arabic: "ٱلْمَلِكُ", transliteration: "Al-Malik", meaning: "The King and Owner of Dominion" },
  { arabic: "ٱلْقُدُّوسُ", transliteration: "Al-Quddūs", meaning: "The Absolutely Pure and Perfect" },
  { arabic: "ٱلسَّلَامُ", transliteration: "As-Salām", meaning: "The Perfection and Giver of Peace" },
  { arabic: "ٱلْمُؤْمِنُ", transliteration: "Al-Mu’min", meaning: "The Granter of Security and Faith" },
  { arabic: "ٱلْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "The Guardian, The Witness, The Overseer" },
  { arabic: "ٱلْعَزِيزُ", transliteration: "Al-‘Azīz", meaning: "The Almighty, The All-Powerful" },
  { arabic: "ٱلْجَبَّارُ", transliteration: "Al-Jabbār", meaning: "The Compeller, The Restorer" },
  { arabic: "ٱلْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "The Supreme, The Majestic" },
  { arabic: "ٱلْخَالِقُ", transliteration: "Al-Khāliq", meaning: "The Creator" },
  { arabic: "ٱلْبَارِئُ", transliteration: "Al-Bāriʾ", meaning: "The Originator" },
  { arabic: "ٱلْمُصَوِّرُ", transliteration: "Al-Muṣawwir", meaning: "The Fashioner, The Shaper" },
  { arabic: "ٱلْغَفَّارُ", transliteration: "Al-Ghaffār", meaning: "The Constant Forgiver" },
  { arabic: "ٱلْقَهَّارُ", transliteration: "Al-Qahhār", meaning: "The All-Prevailing One" },
  { arabic: "ٱلْوَهَّابُ", transliteration: "Al-Wahhāb", meaning: "The Supreme Bestower" },
  { arabic: "ٱلرَّزَّاقُ", transliteration: "Ar-Razzāq", meaning: "The Provider" },
  { arabic: "ٱلْفَتَّاحُ", transliteration: "Al-Fattāḥ", meaning: "The Opener, The Supreme Solver" },
  { arabic: "ٱلْعَلِيمُ", transliteration: "Al-‘Alīm", meaning: "The All-Knowing" },
  { arabic: "ٱلْقَابِضُ", transliteration: "Al-Qābiḍ", meaning: "The Withholder" },
  { arabic: "ٱلْبَاسِطُ", transliteration: "Al-Bāsiṭ", meaning: "The Expander" },
  { arabic: "ٱلْخَافِضُ", transliteration: "Al-Khāfiḍ", meaning: "The Abaser" },
  { arabic: "ٱلْرَّافِعُ", transliteration: "Ar-Rāfiʿ", meaning: "The Exalter" },
  { arabic: "ٱلْمُعِزُّ", transliteration: "Al-Muʿizz", meaning: "The Bestower of Honour" },
  { arabic: "ٱلْمُذِلُّ", transliteration: "Al-Mudhill", meaning: "The Humiliator" },
  { arabic: "ٱلسَّمِيعُ", transliteration: "As-Samīʿ", meaning: "The All-Hearing" },
  { arabic: "ٱلْبَصِيرُ", transliteration: "Al-Baṣīr", meaning: "The All-Seeing" },
  { arabic: "ٱلْحَكَمُ", transliteration: "Al-Ḥakam", meaning: "The Judge" },
  { arabic: "ٱلْعَدْلُ", transliteration: "Al-‘Adl", meaning: "The Utterly Just" },
  { arabic: "ٱلْلَّطِيفُ", transliteration: "Al-Laṭīf", meaning: "The Subtle, The Most Gentle" },
  { arabic: "ٱلْخَبِيرُ", transliteration: "Al-Khabīr", meaning: "The All-Aware" },
  { arabic: "ٱلْحَلِيمُ", transliteration: "Al-Ḥalīm", meaning: "The Most Forbearing" },
  { arabic: "ٱلْعَظِيمُ", transliteration: "Al-‘Aẓīm", meaning: "The Magnificent" },
  { arabic: "ٱلْغَفُورُ", transliteration: "Al-Ghafūr", meaning: "The Forgiving" },
  { arabic: "ٱلشَّكُورُ", transliteration: "Ash-Shakūr", meaning: "The Most Appreciative" },
  { arabic: "ٱلْعَلِيُّ", transliteration: "Al-‘Alī", meaning: "The Most High" },
  { arabic: "ٱلْكَبِيرُ", transliteration: "Al-Kabīr", meaning: "The Most Great" },
  { arabic: "ٱلْحَفِيظُ", transliteration: "Al-Ḥafīẓ", meaning: "The Preserver" },
  { arabic: "ٱلْمُقِيتُ", transliteration: "Al-Muqīt", meaning: "The Nourisher" },
  { arabic: "ٱلْحسِيبُ", transliteration: "Al-Ḥasīb", meaning: "The Reckoner" },
  { arabic: "ٱلْجَلِيلُ", transliteration: "Al-Jalīl", meaning: "The Majestic" },
  { arabic: "ٱلْكَرِيمُ", transliteration: "Al-Karīm", meaning: "The Most Generous" },
  { arabic: "ٱلرَّقِيبُ", transliteration: "Ar-Raqīb", meaning: "The Watchful" },
  { arabic: "ٱلْمُجِيبُ", transliteration: "Al-Mujīb", meaning: "The Responder to Prayer" },
  { arabic: "ٱلْوَاسِعُ", transliteration: "Al-Wāsiʿ", meaning: "The All-Encompassing" },
  { arabic: "ٱلْحَكِيمُ", transliteration: "Al-Ḥakīm", meaning: "The Most Wise" },
  { arabic: "ٱلْوَدُودُ", transliteration: "Al-Wadūd", meaning: "The Most Loving" },
  { arabic: "ٱلْمَجِيدُ", transliteration: "Al-Majīd", meaning: "The Glorious" },
  { arabic: "ٱلْبَاعِثُ", transliteration: "Al-Bāʿith", meaning: "The Resurrector" },
  { arabic: "ٱلشَّهِيدُ", transliteration: "Ash-Shahīd", meaning: "The Witness" },
  { arabic: "ٱلْحَقُّ", transliteration: "Al-Ḥaqq", meaning: "The Truth" },
  { arabic: "ٱلْوَكِيلُ", transliteration: "Al-Wakīl", meaning: "The Trustee" },
  { arabic: "ٱلْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: "The Most Strong" },
  { arabic: "ٱلْمَتِينُ", transliteration: "Al-Matīn", meaning: "The Firm" },
  { arabic: "ٱلْوَلِيُّ", transliteration: "Al-Walīy", meaning: "The Protecting Associate" },
  { arabic: "ٱلْحَمِيدُ", transliteration: "Al-Ḥamīd", meaning: "The Praiseworthy" },
  { arabic: "ٱلْمُحْصِي", transliteration: "Al-Muḥṣī", meaning: "The Accounter" },
  { arabic: "ٱلْمُبْدِئُ", transliteration: "Al-Mubdiʼ", meaning: "The Originator" },
  { arabic: "ٱلْمُعِيدُ", transliteration: "Al-Muʿīd", meaning: "The Restorer" },
  { arabic: "ٱلْمُحْيِي", transliteration: "Al-Muḥyī", meaning: "The Giver of Life" },
  { arabic: "ٱلْمُمِيتُ", transliteration: "Al-Mumīt", meaning: "The Giver of Death" },
  { arabic: "ٱلْحَيُّ", transliteration: "Al-Ḥayy", meaning: "The Ever-Living" },
  { arabic: "ٱلْقَيُّومُ", transliteration: "Al-Qayyūm", meaning: "The Self-Subsisting" },
  { arabic: "ٱلْوَاجِدُ", transliteration: "Al-Wājid", meaning: "The Perceiver" },
  { arabic: "ٱلْمَاجِدُ", transliteration: "Al-Mājid", meaning: "The Illustrious" },
  { arabic: "ٱلْوَاحِدُ", transliteration: "Al-Wāḥid", meaning: "The One" },
  { arabic: "ٱلْأَحَدُ", transliteration: "Al-Aḥad", meaning: "The Unique" },
  { arabic: "ٱلصَّمَدُ", transliteration: "Aṣ-Ṣamad", meaning: "The Satisfier of All Needs" },
  { arabic: "ٱلْقَادِرُ", transliteration: "Al-Qādir", meaning: "The All-Powerful" },
  { arabic: "ٱلْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "The Creator of All Power" },
  { arabic: "ٱلْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "The Promoter" },
  { arabic: "ٱلْمُؤَخِّرُ", transliteration: "Al-Mu’akhkhir", meaning: "The Delayer" },
  { arabic: "اَلْأَوَّلُ", transliteration: "Al-Awwal", meaning: "The First" },
  { arabic: "ٱلآخِرُ", transliteration: "Al-Ākhir", meaning: "The Last" },
  { arabic: "ٱلظَّاهِرُ", transliteration: "Aẓ-Ẓāhir", meaning: "The Manifest" },
  { arabic: "ٱلْبَاطِنُ", transliteration: "Al-Bāṭin", meaning: "The Hidden" },
  { arabic: "ٱلْوَالِي", transliteration: "Al-Wālī", meaning: "The Sole Planner" },
  { arabic: "ٱلْمُتَعَالِي", transliteration: "Al-Mutā‘ālī", meaning: "The Exalted" },
  { arabic: "الْبَرُّ", transliteration: "Al-Barr", meaning: "The Source of Goodness" },
  { arabic: "ٱلْتَّوَّابُ", transliteration: "At-Tawwāb", meaning: "The Ever-Relenting" },
  { arabic: "ٱلْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: "The Avenger" },
  { arabic: "ٱلْعَفُوُّ", transliteration: "Al-‘Afuw", meaning: "The Pardoner" },
  { arabic: "رَبُّ", transliteration: "Rabb", meaning: "The Lord, Sustainer, Cherisher" }
];
